# NPM Parameters
npm:
  server: orion-svr01
  user: test_user
  # pword: xxxx
  ssl_verify: False
  select:
    - Nodes.CustomProperties.Infra_Logical_Location
    - IOSVersion
    - Nodes.CustomProperties.Infra_Location
  where: (Vendor = 'Cisco' or Vendor ='Check Point Software Technologies Ltd') and Nodes.Status = 1

# Filters fed into NPM  Nornir inventory plugin to create the groups
groups:
  - group: ios
    type: switch
    filter: [Catalyst, C9500]
    naplam: ios
    netmiko: cisco_ios
    scrapli: cisco_iosxe
  - group: iosxe
    type: router
    filter: [ASR, CSR]
    naplam: ios
    netmiko: cisco_xe
    scrapli: cisco_iosxe
  - group: nxos
    type: dc_switch
    filter: [Nexus]
    naplam: nxos_ssh
    netmiko: cisco_nxos_ssh
    scrapli: cisco_nxos
  - group: wlc
    type: wifi_controller
    filter: [WLC]
    netmiko: cisco_wlc_ssh
  - group: asa
    type: firewall
    filter: [ASA]
    netmiko: cisco_asa_ssh
# Device username
device:
  user: test_user
#   pword: L00K_pa$$w0rd_github!
